server:
  port: 8765

#url, куда будет происходить регисрация микросервисов и другие важные действия
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: gateway-service
    preferIpAddress: true

#для корректной работы api gateway
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-id
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - AuthenticationFilter
            - RewritePath=/auth/(?<path>.*), /$\{path}
        - id: list-product-id
          uri: lb://list-product-service
          predicates:
            - Path=/list-product/**
          filters:
            - AuthenticationFilter
            - RewritePath=/list-product/(?<path>.*), /$\{path}
        - id: web-client
          uri: lb://web-client
          predicates:
            - Path=/web-client/**
          filters:
            - AuthenticationFilter
            - RewritePath=/web-client/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: auth
        url: /v3/api-docs/auth
      - name: list-product
        url: /v3/api-docs/list-product
