server:
  port: 8761

eureka:
  instance:
    hostname: server-service
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 30
#т.к. это не клиент, то убираем лишние настройки
  client:
    registerWithEureka: false
    fetchRegistry: false
#url, куда будет происходить регисрация микросервисов и другие важные действия
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
