export const SAVE_LIST_REQUEST = "SAVE_LIST_REQUEST";
export const FETCH_LIST_REQUEST = "FETCH_LIST_REQUEST";
export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";

export const FETCH_LANGUAGES_REQUEST = "FETCH_LANGUAGES_REQUEST";
export const LANGUAGES_SUCCESS = "LANGUAGES_SUCCESS";
export const LANGUAGES_FAILURE = "LANGUAGES_FAILURE";

export const FETCH_GENRES_REQUEST = "FETCH_GENRES_REQUEST";
export const GENRES_SUCCESS = "GENRES_SUCCESS";
export const GENRES_FAILURE = "GENRES_FAILURE";
