export const FIND_LIST_REQUEST = "FIND_LIST_REQUEST";
export const SAVE_LIST_REQUEST = "SAVE_LIST_REQUEST";
export const UPDATE_LIST_REQUEST = "UPDATE_LIST_REQUEST";
export const DELETE_LIST_REQUEST = "DELETE_LIST_REQUEST";
export const LIST_SUCCESS = "LIST_SUCCESS";
export const LIST_FAILURE = "LIST_FAILURE";
