#id приложения = желательно указывать всегда в микросервисных приложениях
spring:
  application:
    name: list-product-service
  config:
    import: "optional:configserver:http://localhost:8888"
    activate:
      on-profile: default
---
#id приложения = желательно указывать всегда в микросервисных приложениях
spring:
  application:
    name: list-product-service
  config:
    import: "optional:configserver:http://config-service:8888"
    activate:
      on-profile: docker